# Site setings
name: 'Adam Bujak'
description: 'Hi, my name is Adam and I am a third year mechatronics engineering student at McMaster University.'
logo: 'assets/images/profile.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://adambujak.github.io/
disqus: 'justgoodthemes'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Adam Bujak'
  image: 'authorimage.jpg'

# Contact form setings
email: adamjbujak@gmail.com
contact_page_description: "Feel free to contact me! <br> <br> <a>adamjbujak@gmail.com</a>"

# Social links
github: 'adambujak'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
